//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEIBK.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public long CID { get; set; }
        public long AccID { get; set; }
        public string AccountNumber { get; set; }
        public short AccountType { get; set; }
        public int Branch { get; set; }
        public decimal Balance { get; set; }
        public decimal OverdrawLimit { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<bool> EstatementSub { get; set; }
        public Nullable<int> CurrencyCode { get; set; }
    
        public virtual tblAccountType tblAccountType { get; set; }
        public virtual tblBranchMaster tblBranchMaster { get; set; }
        public virtual tblCurrency tblCurrency { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
