//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEIBK.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCreditCard
    {
        public long ID { get; set; }
        public long CID { get; set; }
        public string CardNumber { get; set; }
        public short ExpMonth { get; set; }
        public short ExpYear { get; set; }
        public short IssueMonth { get; set; }
        public short IssueYear { get; set; }
        public short CVC { get; set; }
        public bool IsPrimary { get; set; }
        public bool IsActive { get; set; }
        public decimal Limit { get; set; }
        public decimal CurrentBalance { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
