//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventAttendances = new HashSet<EventAttendance>();
            this.EventLocations = new HashSet<EventLocation>();
        }
    
        public int ID { get; set; }
        public System.DateTime EventFromDate { get; set; }
        public long EventName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public string Status { get; set; }
        public string FileNameEnglish { get; set; }
        public string FileNameArabic { get; set; }
        public System.DateTime EventToDate { get; set; }
        public string Venue { get; set; }
        public string DetailType { get; set; }
        public string ExternalURL { get; set; }
    
        public virtual ICollection<EventAttendance> EventAttendances { get; set; }
        public virtual ICollection<EventLocation> EventLocations { get; set; }
    }
}
