//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventAttendance
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public long UserID { get; set; }
        public string AttendanceType { get; set; }
        public Nullable<System.DateTime> RegisteredOn { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
