//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMSSection> CMSSections { get; set; }
        public virtual DbSet<CMSSectionType> CMSSectionTypes { get; set; }
        public virtual DbSet<ContactCustomer> ContactCustomers { get; set; }
        public virtual DbSet<ContentType> ContentTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CustomerStory> CustomerStories { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<EventAttendance> EventAttendances { get; set; }
        public virtual DbSet<EventLocation> EventLocations { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<HomeSlider> HomeSliders { get; set; }
        public virtual DbSet<i18n> i18n { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<JobRespons> JobResponses { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<LanguageContent> LanguageContents { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<PhotoGallery> PhotoGalleries { get; set; }
        public virtual DbSet<PhotoGalleryCategory> PhotoGalleryCategories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<ImageContentBox> ImageContentBoxes { get; set; }
        public virtual DbSet<ImageContentBoxType> ImageContentBoxTypes { get; set; }
        public virtual DbSet<PressReleas> PressReleases { get; set; }
        public virtual DbSet<PrivacyPolicy> PrivacyPolicies { get; set; }
    }
}
