//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeSlider
    {
        public long HomeSliderID { get; set; }
        public long SliderTitleTranslationID { get; set; }
        public long SliderSubTitleTranslationID { get; set; }
        public long ButtonTextTranslationID { get; set; }
        public string URL { get; set; }
        public string SliderImage { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public bool IsActive { get; set; }
    }
}
