//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageContentBoxType
    {
        public ImageContentBoxType()
        {
            this.ImageContentBoxes = new HashSet<ImageContentBox>();
        }
    
        public int ImageContentBoxTypeID { get; set; }
        public string ImageContentBoxTypeName { get; set; }
    
        public virtual ICollection<ImageContentBox> ImageContentBoxes { get; set; }
    }
}
