//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobResponses = new HashSet<JobRespons>();
        }
    
        public long JobID { get; set; }
        public long JobTitleTranslationID { get; set; }
        public int CountryID { get; set; }
        public int IndustryID { get; set; }
        public long JobDescriptionTranslationID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Keywords { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Industry Industry { get; set; }
        public virtual ICollection<JobRespons> JobResponses { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
