//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRespons
    {
        public long ResponseID { get; set; }
        public long JobID { get; set; }
        public long UserID { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
