//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageContent
    {
        public long LanguageContentID { get; set; }
        public long TranslationID { get; set; }
        public string LanguageCode { get; set; }
        public string LanguageContent1 { get; set; }
        public int ContentTypeID { get; set; }
    }
}
