//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long NewsID { get; set; }
        public long NewsTitleTranslationID { get; set; }
        public long NewsDescriptionTranslationID { get; set; }
        public Nullable<long> NewsSourceNameTranslationID { get; set; }
        public string NewsSourceLink { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public bool IsActive { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> PressReleaseDate { get; set; }
    }
}
