//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoGalleryCategory
    {
        public PhotoGalleryCategory()
        {
            this.PhotoGalleries = new HashSet<PhotoGallery>();
        }
    
        public int PhotoGalleryCategoryID { get; set; }
        public long CategoryTitleTranslationID { get; set; }
        public long CategoryDescriptionTranslationID { get; set; }
        public string CategoryImage { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
    
        public virtual ICollection<PhotoGallery> PhotoGalleries { get; set; }
    }
}
